# Generated by Django 4.2.16 on 2024-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_purchase_product_purchase_product_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_ids',
            field=models.CharField(db_column='product_ids', help_text='Список ID продуктов через запятую', max_length=255),
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='product_ids',
            new_name='product',
        ),
    ]
